spring:
  application:
    name: gateway

server:
  port: 8080

eureka:
  instance:
    prefer-ip-adress: true
  client:
    service-url:
      defaultZone: http://registry:8081/eureka
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie
  routes:
    todo:
      url: http://main-engine:8082